version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: hotel_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotel123
      POSTGRES_DB: hotel_booking
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
