services:
  db:
    image: postgres:16
    container_name: easy_stay_db
    environment:
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotel123
      POSTGRES_DB: hotel_booking
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
